name: CICDPipeline

on:
  push:
    paths:
      - src/**
    branches:
      - '**'
    tags:
      - 'v*' # Triggers on every version tag push (e.g., v1.0.0)
  pull_request:
    branches:
      - 'main'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Shorten Commit Id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.APP_NAME }}:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}
  
  cd:
    needs: ci
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
      -
        name: Install YT and Modify values file
        shell: bash
        id: modify
        run: |
          NEW_TAG=${{ needs.ci.outputs.commit_id }}
          echo "Deployment tag is: $NEW_TAG"
          #sudo apt update
          sudo apt install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/${{ vars.APP_NAME }}/values.yaml
          cat charts/${{ vars.APP_NAME }}/values.yaml
          
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated values.yaml file with image tag: ${{ needs.ci.outputs.commit_id }}"
      -
        name: Install ArgoCD
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd.svc.cluster.local/download/argocd-linux-arm64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd
      -
        name: ArgoCD Sync App
        shell: bash
        run: |
          argocd login argocd-server.argocd.svc.cluster.local \
          --insecure \
          --grpc-web \
          --username ${{ secrets.ARGOCD_USERNAME }} \
          --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync ${{ vars.APP_NAME }}